### PR TITLE
Send out email on pending approval requests

### PR DESCRIPTION
**Pull request by Zangetsu112**
Please run db migrations again after pulling this in. I had to add 3 tables one each for commandants, major and minor units. The mailers look up the minor unit -> major unit and commandant using the tables. By default any user that logs in is assigned a dummy m[in/aj]or unit and a dummy commandant, we will need to change that (loc: sessions_controller.rb:21) once we have the group data up on app.

### CODE REVIEW

**Comment by evan-krohn** [comment]
Need to switch branch to dev

**Comment by Zangetsu112** [comment]
> Need to switch branch to dev [dev...send_email](https://github.com/jwonnyleaf/Cadet-Activity-Management/compare/dev...send_email)

Changed it to dev. My bad.

**Comment by evan-krohn** [comment]
FYI seeing
```
  Scenario: Send email when creating a new event with all required details # features/notification_on_event.feature:10
    Given the user is on the "New Training Activity" page                  # features/step_definitions/new_events_steps.rb:13
    When the user fills in all required fields with event details          # features/step_definitions/new_events_steps.rb:17
    And the user submits the event creation form                           # features/step_definitions/new_events_steps.rb:26
    Then an email should be sent to the "minor" unit                       # features/step_definitions/notification_steps.rb:1
      expected to find text "To: dummy_minor_unit@tamu.edu" in "Letters Refresh Clear" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/notification_steps.rb:3:in `"an email should be sent to the {string} unit"'
      features/notification_on_event.feature:14:in `an email should be sent to the "minor" unit'
```

**Comment by ndskouby** [comment]
Email functions will not work unless you have properly adjusted your database.
rails db:reset && rails db:seed

**Review by ndskouby — APPROVED** [review]

**Pull request merged**
