### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by devgargd7**
- fix calendar disappearing bug
- fix calendar unit filters
- fix nav bar for small screen
- added Corps of Cadets logo at login screen

### CODE REVIEW

**Comment by jwonnyleaf** [comment]
Is it possible for you to look into why the profile picture is not loading? If not just let me know and I'll push it as is.

**Comment by devgargd7** [comment]
sure, let me have a look

**Comment by devgargd7** [comment]
Seems like the profile picture is being imported from google profile.
So, current_user.profile_picture.present? ? current_user.profile_picture : 'blank-profile-picture.png' results current_user into the profile from the google profile.
I think this is a good way to have, instead to having the user upload their own profiles pics. Thoughts?

**Review by jwonnyleaf — APPROVED** [review]
Everything looks fine. Good work.

**Pull request merged**
